# Generated by Django 5.1.6 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfolio_name_and_multiuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="max_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="min_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
